cabal-version:   3.0
name:            frogos-ir
version:         0.1.0.0
homepage:        https://git.cherdak.work/FrogOS/IR
synopsis:        FrogOS Intermediate Representation types
description:     IR types shared between the FrogOS DSL and Planner.
license:         LGPL-2.1-only
license-file:    LICENSE
author:          Alexandr_Croitor
maintainer:      kroitorsasha06@gmail.com
category:        Language
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options: -Wall

source-repository head
  type:     git
  location: https://git.cherdak.work/FrogOS/IR

library
  import:             warnings
  hs-source-dirs:     src
  default-extensions: StrictData
  exposed-modules:
    Action
    Condition
    Domain.Error
    Domain.Module
    Domain.Module.Forgejo
    Domain.Module.Nginx
    Domain.Module.Nginx.VirtualHost
    Domain.Module.PostgreSQL
    Domain.Module.Virtualization
    Domain.Network
    Domain.Package
    Domain.Power
    Domain.Process
    Domain.System
    Domain.User
    ObserveStrategy
    Policy
    Types

  build-depends:
    , aeson  ^>=2.2
    , base   ^>=4.20.2.0
    , text   ^>=2.1

  default-language:   Haskell2010

test-suite frogos-ir-test
  import:           warnings
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Spec.hs
  other-modules:
    Arbitraries
    Domain.ErrorSpec
    Domain.Module.NginxSpec
    Domain.Module.PostgreSQLSpec
    Domain.ModuleSpec
    Domain.NetworkSpec
    Domain.PackageSpec
    Domain.PowerSpec
    Domain.ProcessSpec
    Domain.SystemSpec
    Domain.UserSpec
    TypesSpec

  build-depends:
    , aeson             ^>=2.2
    , base              ^>=4.20.2.0
    , bytestring        ^>=0.12
    , frogos-ir
    , QuickCheck        ^>=2.14     || ^>=2.15 || ^>=2.16 || ^>=2.17 || ^>=2.18
    , tasty             ^>=1.5
    , tasty-hunit       ^>=0.10
    , tasty-quickcheck  ^>=0.11
    , text              ^>=2.1

  default-language: Haskell2010
